name: Build TrollStore IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew install ldid libarchive openssl@3 pkg-config
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Setup Theos & iOS 16.5 SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/releases/download/iPhoneOS16.5.sdk/iPhoneOS16.5.sdk.tar.xz
          tar -xf iPhoneOS16.5.sdk.tar.xz -C $HOME/theos/sdks
          rm iPhoneOS16.5.sdk.tar.xz

      - name: Build TrollStore
        run: |
          make pre_build make_fastPathSign make_roothelper make_trollstore make_trollhelper_embedded assemble_trollstore

      - name: Package TrollStore IPA
        run: |
          mkdir -p _build/Payload
          cp -r TrollStore/.theos/obj/TrollStore.app _build/Payload/
          cd _build
          zip -vr TrollStore.ipa Payload

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TrollStore-IPA
          path: |
            _build/TrollStore.ipa
            _build/TrollStore.tar
